name: libsecp256k1
version: 0.1.0
synopsis: Bindings for secp256k1
description: Sign and verify signatures using the secp256k1 library.
category: Crypto
author: Keagan McClelland
maintainer: keagan.mcclelland@gmail.com
copyright: (c) 2017 Jean-Pierre Rupp; (c) 2020 Haskoin Developers; (c) 2022 Keagan McClelland
license: MIT
license-file: LICENSE
github: ProofOfKeags/libsecp256k1-haskell.git
homepage: http://github.com/ProofOfKeags/secp256k1-haskell#readme
build-type: Custom
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >=4.9 && <5
  - bytestring >=0.10.8 && <0.12
  - entropy >= 0.3.8 && <0.5
  - hedgehog
  - memory >= 0.14.15 && <1.0
  - transformers >= 0.4.0.0 && <1.0
library:
  source-dirs: src
  cc-options:
  - -DHAVE_CONFIG_H
  - -Wno-error=deprecated-declarations
  c-sources:
  - secp256k1/src/secp256k1.c
  - secp256k1/contrib/lax_der_parsing.c
  - secp256k1/src/precomputed_ecmult.c
  - secp256k1/src/precomputed_ecmult_gen.c
  include-dirs:
  - secp256k1
  - secp256k1/include
tests:
  spec:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - libsecp256k1
      - HUnit

custom-setup:
  dependencies:
  - base >= 4.8 && < 5
  - Cabal >= 1.10